name: check-kicad-title-blocks

on: [push, pull_request]

jobs:
  check-title-blocks:
    name: Check Title Blocks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check Title Blocks
        uses: jtmullen/kicad-title-block-check-action@v2
